.tests:
  stage: test
  before_script:
    - apt-get update -yqq
    - apt-get install git zlib1g-dev -yqq
    - docker-php-ext-install zip
    - pecl install xdebug
    - pecl install trader
    - docker-php-ext-enable trader
    - echo "memory_limit = 256M" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar update
  script:
    - vendor/bin/phpunit --configuration ./phpunit.xml
    - docker-php-ext-enable xdebug
    - vendor/bin/phpunit --coverage-text --colors=never --configuration ./phpunit_coverage.xml
  cache:
    paths:
      - vendor/

test:7.0:
  image: php:7.0
  extends: .tests
test:7.1:
  image: php:7.1
  extends: .tests
test:7.2:
  image: php:7.2
  extends: .tests
