.tests:
  stage: test
  before_script:
    - apt-get update -yqq
    - apt-get install git zlib1g-dev -yqq
    - docker-php-ext-install zip
    - pecl install xdebug
    - pecl install trader
    - docker-php-ext-enable xdebug
    - docker-php-ext-enable trader
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar update
  script:
    - vendor/bin/phpunit --configuration ./phpunit.xml
    - docker-php-ext-enable xdebug
    - vendor/bin/phpunit --coverage-text --colors=never --configuration ./phpunit_coverage.xml
  cache:
    paths:
      - vendor/

test:7.0-nts:
  image: php:7.0
  extends: .tests
test:7.1-nts:
  image: php:7.1
  extends: .tests
test:7.2-nts:
  image: php:7.2
  extends: .tests
test:7.0-zts:
  image: php:7.0-zts
  extends: .tests
test:7.1-zts:
  image: php:7.1-zts
  extends: .tests
test:7.2-zts:
  image: php:7.2-zts
  extends: .tests
